#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\SingleCommandApplication;
use Akihisa1210\Oyaoya\Processor;

(new SingleCommandApplication())
    ->setName('Oyaoya')
    ->setVersion('1.0.0')
    ->setCode(function (InputInterface $input, OutputInterface $output): int {
        $text = stream_get_contents(STDIN);
        $processor = new Processor($text);
        $output->writeln("NICOLA: " . $processor->countInNICOLA());
        $output->writeln("Romaji: " . $processor->countInRomaji());
        return 0;
    })
    ->run();
