#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\SingleCommandApplication;
use Akihisa1210\Oyaoya\UseCase\ShowKeystrokesUseCase;

(new SingleCommandApplication())
    ->setName('Oyaoya')
    ->setVersion('1.0.0')
    ->addArgument('text', InputArgument::OPTIONAL, 'Text to count')
    ->setCode(function (InputInterface $input, OutputInterface $output): int {
        $text = $input->getArgument('text') ?? stream_get_contents(STDIN);

        $show_keystrokes = new ShowKeystrokesUseCase();
        $result = $show_keystrokes->execute($text);

        foreach ($result->get() as $input_method => $count) {
            $output->writeln($input_method . ": " . $count);
        }

        return 0;
    })
    ->run();
